# Generated by Django 5.2 on 2025-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
